version: "3"
services:
  server:
    container_name: flask
    build: .
    ports: ['5000:5000']
    volumes: ['.:/usr/local/src']
    restart: always
    environment:
      ENV: DEVELOPMENT
      DB_USERNAME: appuser
      DB_PASSWORD: appuser
      DB_DATABASE: mydb
      DB_HOST: localhost
    links:
      - database
  database:
    container_name: database
    image: mysql:5.7
    restart: always
    environment:
      MYSQL_DATABASE: mydb
      MYSQL_USER: appuser
      MYSQL_PASSWORD: appuser
      MYSQL_ROOT_PASSWORD: root
    ports:
      - '3306:3306'
    expose:
      - '3306'
    volumes:
      - flask-db:/var/lib/mysql
      - ./db_seed.sql:/docker-entrypoint-initdb.d/db_seed.sql
volumes:
  flask-db:
